/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ForgotPassword.java
 *
 * Created on Jan 11, 2016, 1:12:48 PM
 */
package gui;

import management.LoginManagement;
import management.Response;
import config.Configuration;
import javax.swing.JOptionPane;

/**
 *
 * @author nishant
 */
public class ForgotPassword extends javax.swing.JFrame {

    /** Creates new form ForgotPassword */
    public ForgotPassword() {
        initComponents();
        questionComboBox.setModel(new javax.swing.DefaultComboBoxModel(Configuration.questions));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        forgotPasswordLabel = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        answerLabel = new javax.swing.JLabel();
        questionComboBox = new javax.swing.JComboBox();
        answerField = new javax.swing.JTextField();
        proceedButton = new javax.swing.JButton();
        backLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 250, 0, 0));

        forgotPasswordLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        forgotPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotPasswordLabel.setText("Forgot Password ? Answer your Security Question");
        forgotPasswordLabel.setBounds(45, 10, 380, 20);
        jLayeredPane1.add(forgotPasswordLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        questionLabel.setFont(new java.awt.Font("Ubuntu", 1, 15));
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        questionLabel.setText("Question");
        questionLabel.setBounds(10, 50, 80, 20);
        jLayeredPane1.add(questionLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        answerLabel.setFont(new java.awt.Font("Ubuntu", 1, 15));
        answerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        answerLabel.setText("Answer");
        answerLabel.setBounds(10, 90, 80, 20);
        jLayeredPane1.add(answerLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        questionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        questionComboBox.setBounds(110, 48, 330, 28);
        jLayeredPane1.add(questionComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        answerField.setBounds(110, 88, 330, 28);
        jLayeredPane1.add(answerField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        proceedButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        proceedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/rsz_1proceed.png"))); // NOI18N
        proceedButton.setText("Proceed");
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });
        proceedButton.setBounds(160, 130, 150, 30);
        jLayeredPane1.add(proceedButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/go-previous.png"))); // NOI18N
        backLabel.setText("Back");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });
        backLabel.setBounds(20, 135, 70, 20);
        jLayeredPane1.add(backLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
    this.dispose();
    login.setVisible(true);
}//GEN-LAST:event_backLabelMouseClicked

private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
    String question = questionComboBox.getSelectedItem().toString();
    LoginManagement loginManagement = new LoginManagement();
    Response response = new Response();
    
    if(formComplete()) { 
        response = loginManagement.checkValidity(handle, question, answerField.getText());
        if(response.responseCode == 0) {
            this.hide();
            ResetPassword resetPassword = new ResetPassword();
            resetPassword.setVisible(true);
            resetPassword.takeForgotPasswordObject(this);
        }
        else {
            JOptionPane.showMessageDialog(rootPane, response.responseMessage);
        }
    }
}//GEN-LAST:event_proceedButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerField;
    private javax.swing.JLabel answerLabel;
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton proceedButton;
    private javax.swing.JComboBox questionComboBox;
    private javax.swing.JLabel questionLabel;
    // End of variables declaration//GEN-END:variables

    Login login;
    String handle;
    void takeLoginObject(Login login, String handle) {
        this.login = login;
        this.handle = handle;
    }

    private boolean formComplete() {
        if(answerField.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Answer field cannot be left blank");
            return false;
        }
        return true;
    }
}
