/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Register.java
 *
 * Created on Jan 9, 2016, 1:39:50 AM
 */
package gui;

import config.Configuration;
import entities.User;
import javax.swing.JOptionPane;
import management.LoginManagement;

/**
 *
 * @author nishant
 */
public class Register extends javax.swing.JFrame {

    /** Creates new form Register */
    public Register() {
        initComponents();
        securityQuesComboBox.setModel(new javax.swing.DefaultComboBoxModel(Configuration.questions));
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel(Configuration.gender));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        registerLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        answerLabel = new javax.swing.JLabel();
        securityQuestionLabel = new javax.swing.JLabel();
        confirmPasswordLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        handleLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        handleField = new javax.swing.JTextField();
        answerField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox();
        securityQuesComboBox = new javax.swing.JComboBox();
        confirmPasswordField = new javax.swing.JPasswordField();
        passwordField = new javax.swing.JPasswordField();
        backLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 250, 0, 0));

        registerLabel.setFont(new java.awt.Font("Ubuntu", 1, 17));
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setText("Registration Form");
        registerLabel.setBounds(129, 10, 199, 20);
        jLayeredPane1.add(registerLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        genderLabel.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        genderLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        genderLabel.setText("Gender");
        genderLabel.setBounds(20, 220, 90, 20);
        jLayeredPane1.add(genderLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        answerLabel.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        answerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        answerLabel.setText("Answer");
        answerLabel.setBounds(10, 300, 100, 20);
        jLayeredPane1.add(answerLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        securityQuestionLabel.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        securityQuestionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        securityQuestionLabel.setText("Security Ques.");
        securityQuestionLabel.setBounds(10, 260, 100, 20);
        jLayeredPane1.add(securityQuestionLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        confirmPasswordLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        confirmPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        confirmPasswordLabel.setText("Confirm Again");
        confirmPasswordLabel.setBounds(0, 170, 110, 20);
        jLayeredPane1.add(confirmPasswordLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        passwordLabel.setFont(new java.awt.Font("Ubuntu", 1, 16));
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordLabel.setText("Password");
        passwordLabel.setBounds(20, 130, 90, 20);
        jLayeredPane1.add(passwordLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        handleLabel.setFont(new java.awt.Font("Ubuntu", 1, 16));
        handleLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        handleLabel.setText("Handle");
        handleLabel.setBounds(20, 90, 90, 20);
        jLayeredPane1.add(handleLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nameLabel.setFont(new java.awt.Font("Ubuntu", 1, 16));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLabel.setText("Name");
        nameLabel.setBounds(20, 50, 90, 20);
        jLayeredPane1.add(nameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        submitButton.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        submitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/rsz_ok.png"))); // NOI18N
        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        submitButton.setBounds(159, 340, 139, 35);
        jLayeredPane1.add(submitButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handleField.setBounds(130, 88, 300, 28);
        jLayeredPane1.add(handleField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        answerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerFieldActionPerformed(evt);
            }
        });
        answerField.setBounds(130, 298, 300, 28);
        jLayeredPane1.add(answerField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nameField.setBounds(130, 48, 300, 28);
        jLayeredPane1.add(nameField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        genderComboBox.setBounds(130, 218, 100, 28);
        jLayeredPane1.add(genderComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        securityQuesComboBox.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        securityQuesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        securityQuesComboBox.setBounds(130, 258, 300, 26);
        jLayeredPane1.add(securityQuesComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        confirmPasswordField.setBounds(130, 168, 300, 28);
        jLayeredPane1.add(confirmPasswordField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        passwordField.setBounds(130, 128, 300, 28);
        jLayeredPane1.add(passwordField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/go-previous.png"))); // NOI18N
        backLabel.setText("Back");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });
        backLabel.setBounds(10, 350, 70, 20);
        jLayeredPane1.add(backLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void answerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerFieldActionPerformed
}//GEN-LAST:event_answerFieldActionPerformed

private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
    this.dispose();
    login.setVisible(true);
}//GEN-LAST:event_backLabelMouseClicked

private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
// TODO add your handling code here:
    if(formComplete()) {
        try {
            LoginManagement loginManagement = new LoginManagement();
            
            if(loginManagement.searchHandle(handleField.getText()) == false) {
                if(loginManagement.registerUser(new User(handleField.getText(), nameField.getText(),
                        passwordField.getText(), securityQuesComboBox.getSelectedItem().toString(),
                        answerField.getText(), genderComboBox.getSelectedItem().toString()))) {
                    this.dispose();
                    login.setVisible(true);
                }
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "This handle is already taken");
            }
        } catch(Exception exception) {
            JOptionPane.showMessageDialog(rootPane, "Client : " + exception.getMessage());
        }
    }
}//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Register().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerField;
    private javax.swing.JLabel answerLabel;
    private javax.swing.JLabel backLabel;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JComboBox genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField handleField;
    private javax.swing.JLabel handleLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JComboBox securityQuesComboBox;
    private javax.swing.JLabel securityQuestionLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
    
    Login login;
    void takeLoginObject(Login login) {
        this.login = login;
    }

    private boolean formComplete() {
        if(nameField.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Name field cannot be left blank");
            return false;
        }
        if(handleField.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Handle field cannot be left blank");
            return false;
        }
        if(passwordField.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Password field cannot be left blank");
            return false;
        }
        if(confirmPasswordField.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Confirm your password");
            return false;
        }
        if(answerField.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Answer field cannot be left blank");
            return false;
        }
        if(passwordField.getText().equals(confirmPasswordField.getText()) == false) {
            JOptionPane.showMessageDialog(rootPane, "Passwords do not match");
            return false;
        }
        return true;
    }
}
