/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResetPassword.java
 *
 * Created on Jan 11, 2016, 4:54:28 PM
 */
package gui;

import javax.swing.JOptionPane;
import management.LoginManagement;

/**
 *
 * @author nishant
 */
public class ResetPassword extends javax.swing.JFrame {

    /** Creates new form ResetPassword */
    public ResetPassword() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        resetPasswordLabel = new javax.swing.JLabel();
        confirmPasswordLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        newPasswordField = new javax.swing.JPasswordField();
        resetPasswordButton = new javax.swing.JButton();
        backLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 250, 0, 0));

        resetPasswordLabel.setFont(new java.awt.Font("Ubuntu", 1, 17));
        resetPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resetPasswordLabel.setText("Reset Password");
        resetPasswordLabel.setBounds(125, 10, 150, 20);
        jLayeredPane1.add(resetPasswordLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        confirmPasswordLabel.setFont(new java.awt.Font("Ubuntu", 1, 15));
        confirmPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        confirmPasswordLabel.setText("Confirm Password");
        confirmPasswordLabel.setBounds(0, 90, 140, 20);
        jLayeredPane1.add(confirmPasswordLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        newPasswordLabel.setFont(new java.awt.Font("Ubuntu", 1, 15));
        newPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        newPasswordLabel.setText("New Password");
        newPasswordLabel.setBounds(10, 50, 130, 20);
        jLayeredPane1.add(newPasswordLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        confirmPasswordField.setBounds(160, 87, 220, 28);
        jLayeredPane1.add(confirmPasswordField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        newPasswordField.setBounds(160, 47, 220, 28);
        jLayeredPane1.add(newPasswordField, javax.swing.JLayeredPane.DEFAULT_LAYER);

        resetPasswordButton.setFont(new java.awt.Font("Ubuntu", 1, 16));
        resetPasswordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/rsz_reset.png"))); // NOI18N
        resetPasswordButton.setText("Reset my Password");
        resetPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPasswordButtonActionPerformed(evt);
            }
        });
        resetPasswordButton.setBounds(100, 140, 200, 30);
        jLayeredPane1.add(resetPasswordButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/go-previous.png"))); // NOI18N
        backLabel.setText("Back");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });
        backLabel.setBounds(10, 145, 70, 20);
        jLayeredPane1.add(backLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
// TODO add your handling code here:
    this.dispose();
    forgotPassword.setVisible(true);
}//GEN-LAST:event_backLabelMouseClicked

private void resetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordButtonActionPerformed
    if(formComplete()) {
        if(newPasswordField.getText().equals(confirmPasswordField.getText())) {
            LoginManagement loginManagement = new LoginManagement();
            
            try {
                if(loginManagement.resetPassword(handle, newPasswordField.getText())) {
                    this.dispose();
                    new Login().setVisible(true);
                }
            } catch(Exception exception) {
                JOptionPane.showMessageDialog(rootPane, "Client : " + exception.getMessage());
            }
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Passwords do not match");
        }
    }
}//GEN-LAST:event_resetPasswordButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ResetPassword().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLabel;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JButton resetPasswordButton;
    private javax.swing.JLabel resetPasswordLabel;
    // End of variables declaration//GEN-END:variables

    ForgotPassword forgotPassword;
    String handle;
    void takeForgotPasswordObject(ForgotPassword forgotPassword, String handle) {
        this.forgotPassword = forgotPassword;
        this.handle = handle;
    }

    private boolean formComplete() {
        if(newPasswordField.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please provide your New Password");
            return false;
        }
        if(confirmPasswordField.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please confirm your password again");
            return false;
        }
        return true;
    }
}
